version: 2.0

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3072m -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          
      - run:
          name: Assemble APKs
          command: ./gradlew assembleDebug --no-daemon
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks

      - run:
          name: Check
          command: ./gradlew check --no-daemon
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
          